BestPrice/Supermarket/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="home"),
    path('basket/', include("basket.urls")),
    path('products/', include("products.urls")),
    path('accounts/', include("accounts.urls")),
]

# It is inefficient to use Django to load in static file when in production.
# thats why firms use AWS.
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BestPrice/accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"

urlpatterns = [
 path('register/', views.register_page, name="register"),
 path('login/', views.login_page, name="login"),
 path('logout/', views.logout_page, name="logout")
]

BestPrice/basket/urls.py
from django.urls import path, re_path
from . import views

app_name = "basket"

urlpatterns = [
    path('basket/', views.basket_view, name="basket"),
    re_path(r'(?P<slug>[\w-]+)/', views.update_basket, name="update")
]

BestPrice/products/urls.py
from django.urls import path, re_path
from . import views

app_name = "products"

urlpatterns = [
    path('main/', views.main_products, name="main"),
    path('categories/', views.categories, name="categories"),
    re_path(r'categories/(?P<category_slug>[-\w]+)/', views.filtered_products, name="filtered_products"),
]

BestPrice/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'banner-styles.css' %}">
  </head>
  <header>
    <div class="logo-image">
      <h1><a href="{% url 'home' %}"><img src="{% static 'BestPrice.jpeg'%}" width="200" height="50" alt="SuperMarkIt"/></a></h1>
    </div>



    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'products:categories' %}" class="tag-categories-base">Categories</a></li>
          <li><a href="{% url 'products:main' %}" class="tag-products-base">Products</a></li>
          <li><a href="{% url 'basket:basket' %}" class="tag-basket-base">Basket</a></li>
          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" name="btn-logout">Logout</button>
            </form>
          </li>
        {% else %}


        {% endif %}
      </ul>





    </nav>


  </header>
  <body>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

BestPrice/templates/homepage.html
{% extends 'base_layout.html' %}
{% load static %}

<!DOCTYPE html>
{% block content %}
  <head>
    <meta charset="utf-8">
    <title>BestPrice</title>
    <link rel="stylesheet" href="{% static 'homepage-styles.css' %}">
  </head>
  <body>
    <section class="hero">
      <div class="site-description">
        <h2>E-commerce Price comparision</h2>
        <h3><font color="white">Shop with a difference</font></h3>
        {% if user.is_authenticated %}

        {% else %}
        <a href="{% url 'accounts:login' %}" class="tag-login-base">Login</a>
        <a href="{% url 'accounts:register' %}" class="tag-register-base">Register</a>
        {% endif %}
      </div>
    </section>
    <span class="created-by"><p>Created by Team - 3088</p></span>
  </body>
{% endblock %}