BestPrice/Supermarket/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="home"),
    path('basket/', include("basket.urls")),
    path('products/', include("products.urls")),
    path('accounts/', include("accounts.urls")),
]

# It is inefficient to use Django to load in static file when in production.
# thats why firms use AWS.
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BestPrice/basket/urls.py
from django.urls import path, re_path
from . import views

app_name = "basket"

urlpatterns = [
    path('basket/', views.basket_view, name="basket"),
    re_path(r'(?P<slug>[\w-]+)/', views.update_basket, name="update")
]

BestPrice/products/urls.py
from django.urls import path, re_path
from . import views

app_name = "products"

urlpatterns = [
    path('main/', views.main_products, name="main"),
    path('categories/', views.categories, name="categories"),
    re_path(r'categories/(?P<category_slug>[-\w]+)/', views.filtered_products, name="filtered_products"),
]

BestPrice/products/models.py
from django.db import models
from django.urls import reverse
# Create your models here.




class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    thumbnail = models.ImageField(default='default-product.png', blank=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('products:filtered_products', args=[self.slug])



    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=50, db_index=True)

    url_morrisons = models.CharField(max_length=250, db_index=True)
    url_sainsburys = models.CharField(max_length=250, db_index=True)
    url_tesco = models.CharField(max_length=250, db_index=True)

    price_morrisons = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    price_sainsburys = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    price_tesco = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    thumbnail = models.ImageField(default='default-product.png', blank=True)
    # make all thumbnails at most 140x140pixels

    class Meta:
        ordering = ('name', )
<<<<<<< HEAD
        indexes = [
            models.Index(fields=['id', 'slug']),
        ]
=======
        index_together = (('id', 'slug'),)
>>>>>>> be08d98730b581d040c432365cebcb1271a58c1f

    def __str__(self):
        return self.name

BestPrice/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category


def filtered_products(request, category_slug):
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    print(category, products)
    template = "products/categories/filter.html"
    context = {"categories": categories, "product_query_set": products, "category": category}
    return render(request, template, context)


def main_products(request):
    products = Product.objects.all()
    return render(request, "products/main_products.html", {"products": products})


def categories(request):
    categories = Category.objects.all()
    return render(request, "products/categories.html", {"categories": categories})

BestPrice/products/templates/products/categories/filter.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}

  <title>{{category.name}}</title>
  <h1>{{category.name}}</h1>
  <h1>{{product.category}}</h1>
  <link rel="stylesheet" href="{% static 'products/filtered-products.css' %}">
  <div class="Products">

    {% for product in product_query_set %}
      <div class="product">
        <img src="{{product.thumbnail.url}}" class="thumbnails">
        <h5>{{product.name}}</h5>
          <span class="Tesco">Amazon:</span>
            <span class="product-price"> &nbsp;
               Rs{{product.price_tesco}}</span><br>
          <span class="Sainsburys">FlipKart:</span>
            <span class="product-price"> &nbsp; Rs{{product.price_sainsburys}}</span><br>
          <span class="Morrisons">JioMart:</span>
            <span class="product-price"> &nbsp;&nbsp;
               Rs{{product.price_morrisons}}</span><br>
        <br>
        <form class="attibute-qty" action="{% url 'basket:update' product.slug %}" method="GET">
          <span class="units-qty">Quantity: </span><input type="number" name="quantity" placeholder="1" min="1" max="8" oninput="this.value = Math.abs(this.value)">
          <button type="submit" class="btn-add-to-basket"><span>Add to Basket</span></button>
        </form>
      </div>
    {% endfor %}
  </div>
{% endblock %}